In [23]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [63]:
sig = 0.5
rho=1
nsim = 1000
Tvec = [10,25,50,100,250]
nvec = [1,2,3,5,10]
holding_place = np.zeros((nsim,len(Tvec),len(nvec)))
for ndx,n in enumerate(nvec):
    for tdx,T in enumerate(Tvec):
        for isim in range(nsim):
            y = np.random.normal(0,sig,size=(T+100,1))
            for t in range(1,T+100):
                y[t] += rho*y[t-1]
            x = np.random.normal(0,sig,size=(T+100,n))
            for t in range(1,T+100):
                x[t] += rho*x[t-1]
            x = sm.add_constant(x)
            model = smf.OLS(y,x).fit()
            #np.vstack((x.mean(0),x.std(0))).T
            holding_place[isim,tdx,ndx] = model.rsquared
print(holding_place.mean(0))

[[0.22184821 0.38875925 0.50584353 0.65140019 0.78877034]
 [0.23694589 0.402169   0.51762008 0.63139547 0.79029553]
 [0.23924125 0.41080148 0.51501152 0.65317522 0.78573653]
 [0.23488156 0.38744531 0.51193029 0.63524951 0.78631503]
 [0.23412321 0.3892416  0.50627958 0.63195179 0.78415622]]


In [64]:
sig = 0.5
rho=1
nsim = 1000
Tvec = [10,25,50,100,250]
nvec = [1,2,3,5,10]
holding_place = np.zeros((nsim,len(Tvec),len(nvec)))
for ndx,n in enumerate(nvec):
    for tdx,T in enumerate(Tvec):
        for isim in range(nsim):
            y = np.random.normal(0,sig,size=(T+100,1))
            x = np.random.normal(0,sig,size=(T+100,n))
            x = sm.add_constant(x)
            model = smf.OLS(y,x).fit()
            #np.vstack((x.mean(0),x.std(0))).T
            holding_place[isim,tdx,ndx] = model.rsquared
print(holding_place.mean(0))

[[0.00917212 0.01739606 0.02780322 0.04516604 0.09197386]
 [0.00831447 0.01661638 0.0245718  0.03990989 0.07907376]
 [0.00641464 0.01321495 0.02013397 0.03268059 0.06570967]
 [0.00487562 0.00980557 0.01476621 0.02487284 0.04970818]
 [0.00270889 0.00598487 0.00822677 0.01439156 0.02857625]]
