In [2]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf

C:\Anaconda\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools


In [4]:
sig = 0.5
nsim = 1000
Tvec = [10,25,50,100,250]
nvec = [1,2,3,5,10]
holding_place = np.zeros((nsim,len(Tvec),len(nvec)))
for ndx,n in enumerate(nvec):
    for tdx,T in enumerate(Tvec):
        for isim in range(nsim):
            y = np.random.normal(0,sig,size=(T,1))
            x = np.random.normal(0,sig,size=(T,n))
            x = sm.add_constant(x)
            model = smf.OLS(y,x).fit()
            #np.vstack((x.mean(0),x.std(0))).T
            holding_place[isim,tdx,ndx] = model.rsquared 
print(holding_place.mean(0))

[[ 0.10555896  0.22415646  0.34322405  0.55030806  1.        ]
 [ 0.04394012  0.08193936  0.12325001  0.20225609  0.42510906]
 [ 0.01983272  0.04106161  0.06031676  0.10153808  0.20388295]
 [ 0.01004529  0.02106374  0.02895429  0.05159638  0.10192699]
 [ 0.00379237  0.00816725  0.01228554  0.02046998  0.03995487]]


In [74]:
T=50
sig=0.5
rho=0.75
y = np.random.normal(0,sig,size=(T+100,1))
for t in range(1,T+100):
    y[t] += rho*y[t-1]
y = y[100:]
y_0 = y[2:T]
y_1 = y[1:T-1]
xdata = sm.add_constant(y_1)
smf.OLS(y_0,y_1).fit().params
smf.OLS(y_0,xdata).fit().params
#0.5657013738527894*0.75**2+0.25

array([-0.06665154,  0.68234313])