In [1]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [3]:
sig = 0.5
nsim = 1000
Tvec = [10,25,50,100,250]
nvec = [1,2,3,5,10]
holding_place_3b = np.zeros((nsim,len(Tvec),len(nvec)))
for ndx,n in enumerate(nvec):
    for tdx,T in enumerate(Tvec):
        for isim in range(nsim):
            y = np.random.normal(0,sig,size=(T,1))
            x = np.random.normal(0,sig,size=(T,n))
            x = sm.add_constant(x)
            model = smf.OLS(y,x).fit()
            #np.vstack((x.mean(0),x.std(0))).T
            holding_place_3b[isim,tdx,ndx] = model.rsquared
print(holding_place_3b.mean(0))

[[ 0.10731999  0.23452948  0.32507434  0.54655264  1.        ]
 [ 0.04035316  0.08516739  0.12803505  0.20180759  0.40781903]
 [ 0.02011455  0.03998148  0.0601018   0.10348634  0.20135053]
 [ 0.01040135  0.02009187  0.02938352  0.04961028  0.10239339]
 [ 0.00362822  0.00826317  0.01187549  0.02054922  0.03941669]]


In [5]:
pd.DataFrame(holding_place_3b.mean(0))

0         1         2         3         4
0  0.107320  0.234529  0.325074  0.546553  1.000000
1  0.040353  0.085167  0.128035  0.201808  0.407819
2  0.020115  0.039981  0.060102  0.103486  0.201351
3  0.010401  0.020092  0.029384  0.049610  0.102393
4  0.003628  0.008263  0.011875  0.020549  0.039417

In [2]:
sig = 0.5
nsim = 1000
Tvec = [10,25,50,100,250]
nvec = [1,2,3,5,10]
holding_place = np.zeros((nsim,len(Tvec),len(nvec)))
for ndx,n in enumerate(nvec):
    for tdx,T in enumerate(Tvec):
        for isim in range(nsim):
            y = np.random.normal(0,sig,size=(T,1))
            x = np.random.normal(0,sig,size=(T,n))
            for t in range(1,T):
                y[t] += y[t-1]
                x[t,:] += x[t-1,:]
            x = sm.add_constant(x)
            model = smf.OLS(y,x).fit()
            #np.vstack((x.mean(0),x.std(0))).T
            holding_place[isim,tdx,ndx] = model.rsquared
print(holding_place.mean(0))

[[ 0.26493629  0.45842413  0.58140814  0.77346536  1.        ]
 [ 0.24047314  0.41425207  0.53203694  0.66332728  0.82257341]
 [ 0.24006665  0.39804593  0.49327777  0.63750289  0.7911114 ]
 [ 0.24574455  0.38891236  0.51512421  0.63490454  0.79255821]
 [ 0.2444314   0.41039574  0.50260268  0.64344959  0.77650541]]


In [6]:
pd.DataFrame(holding_place.mean(0))

0         1         2         3         4
0  0.264936  0.458424  0.581408  0.773465  1.000000
1  0.240473  0.414252  0.532037  0.663327  0.822573
2  0.240067  0.398046  0.493278  0.637503  0.791111
3  0.245745  0.388912  0.515124  0.634905  0.792558
4  0.244431  0.410396  0.502603  0.643450  0.776505

In [20]:
nsim = 500
Tvec = [10,25,50,100]
rvec = [0.3,0.4,0.5,0.6,0.7,0.8,0.9]
svec = [0.5,1,2]

outp = np.zeros((len(Tvec)*len(rvec)*len(svec),nsim,5))
rowcnt = 0
for T in Tvec:
    for sig in svec:
        for rho in rvec:
            for isim in range(nsim):
                y = np.random.normal(0,sig,size=(T+100,1))
                for t in range(1,T+100):
                    y[t] += rho*y[t-1]
                y = y[100:]
                y_0 = y[2:T]
                y_1 = y[1:T-1]
                xdata = sm.add_constant(y_1)
                outp[rowcnt,isim,0] = T
                outp[rowcnt,isim,1] = sig
                outp[rowcnt,isim,2] = rho
                outp[rowcnt,isim,3] = smf.OLS(y_0,y_1).fit().params
                outp[rowcnt,isim,4] = smf.OLS(y_0,xdata).fit().params[1]
            rowcnt += 1
outp.mean(1)
#0.5657013738527894*0.75**2+0.25

array([[  1.00000000e+01,   5.00000000e-01,   3.00000000e-01,
          2.46314838e-01,   8.64820462e-02],
       [  1.00000000e+01,   5.00000000e-01,   4.00000000e-01,
          3.32108496e-01,   1.52568284e-01],
       [  1.00000000e+01,   5.00000000e-01,   5.00000000e-01,
          4.03716532e-01,   1.95610024e-01],
       [  1.00000000e+01,   5.00000000e-01,   6.00000000e-01,
          5.12877692e-01,   2.73455410e-01],
       [  1.00000000e+01,   5.00000000e-01,   7.00000000e-01,
          6.01165733e-01,   3.36957982e-01],
       [  1.00000000e+01,   5.00000000e-01,   8.00000000e-01,
          6.85159983e-01,   4.14603444e-01],
       [  1.00000000e+01,   5.00000000e-01,   9.00000000e-01,
          7.91406045e-01,   4.48606258e-01],
       [  1.00000000e+01,   1.00000000e+00,   3.00000000e-01,
          2.29035011e-01,   7.17117977e-02],
       [  1.00000000e+01,   1.00000000e+00,   4.00000000e-01,
          3.40486710e-01,   1.50223840e-01],
       [  1.00000000e+01,   1.0000000

In [9]:
smf.OLS(y_0,xdata).fit().params[1]

0.6942819769082923

In [8]:
pd.DataFrame(outp.mean(1))

0    1     2         3         4
0    10.0  0.5  0.25  0.220895  0.051064
1    10.0  0.5  0.50  0.440928  0.271271
2    10.0  0.5  0.75  0.634751  0.393820
3    10.0  1.0  0.25  0.207696  0.079546
4    10.0  1.0  0.50  0.483247  0.224649
5    10.0  1.0  0.75  0.681801  0.372425
6    10.0  2.0  0.25  0.223380  0.057748
7    10.0  2.0  0.50  0.413237  0.197907
8    10.0  2.0  0.75  0.646836  0.399285
9    25.0  0.5  0.25  0.204980  0.157085
10   25.0  0.5  0.50  0.494664  0.425930
11   25.0  0.5  0.75  0.678030  0.591780
12   25.0  1.0  0.25  0.261610  0.205375
13   25.0  1.0  0.50  0.433638  0.357598
14   25.0  1.0  0.75  0.688754  0.619128
15   25.0  2.0  0.25  0.237090  0.181178
16   25.0  2.0  0.50  0.425784  0.367187
17   25.0  2.0  0.75  0.676156  0.583743
18   50.0  0.5  0.25  0.242393  0.223510
19   50.0  0.5  0.50  0.489330  0.457222
20   50.0  0.5  0.75  0.712644  0.674081
21   50.0  1.0  0.25  0.238020  0.207063
22   50.0  1.0  0.50  0.483318  0.460370
23   50.0  1.0  0.75  0.737675  0.692284
24   50.0  2.0  0.25  0.255838  0.225221
25   50.0  2.0  0.50  0.491263  0.458919
26   50.0  2.0  0.75  0.712614  0.657389
27  100.0  0.5  0.25  0.264951  0.253175
28  100.0  0.5  0.50  0.490708  0.478704
29  100.0  0.5  0.75  0.740569  0.719161
30  100.0  1.0  0.25  0.238534  0.226298
31  100.0  1.0  0.50  0.504751  0.491685
32  100.0  1.0  0.75  0.733899  0.718925
33  100.0  2.0  0.25  0.236149  0.224274
34  100.0  2.0  0.50  0.489858  0.476768
35  100.0  2.0  0.75  0.729638  0.711186

In [21]:
df = pd.DataFrame(np.hstack((outp.mean(1),outp.var(1)[:,3:])))
df.columns = ('sample','sig','rho','E_b_nocon','E_b_con','V_b_nocon','V_b_con')
df

sample  sig  rho  E_b_nocon   E_b_con  V_b_nocon   V_b_con
0     10.0  0.5  0.3   0.246315  0.086482   0.106201  0.123817
1     10.0  0.5  0.4   0.332108  0.152568   0.099394  0.115257
2     10.0  0.5  0.5   0.403717  0.195610   0.091637  0.119619
3     10.0  0.5  0.6   0.512878  0.273455   0.088168  0.122184
4     10.0  0.5  0.7   0.601166  0.336958   0.080530  0.121818
5     10.0  0.5  0.8   0.685160  0.414603   0.068741  0.123253
6     10.0  0.5  0.9   0.791406  0.448606   0.065082  0.141322
7     10.0  1.0  0.3   0.229035  0.071712   0.105965  0.112917
8     10.0  1.0  0.4   0.340487  0.150224   0.099926  0.122615
9     10.0  1.0  0.5   0.412121  0.223027   0.091366  0.119283
10    10.0  1.0  0.6   0.498088  0.277187   0.081828  0.120017
11    10.0  1.0  0.7   0.607656  0.340025   0.071638  0.115511
12    10.0  1.0  0.8   0.691789  0.415262   0.071635  0.136523
13    10.0  1.0  0.9   0.763677  0.464842   0.068238  0.127172
14    10.0  2.0  0.3   0.245484  0.064765   0.098497  0.111107
15    10.0  2.0  0.4   0.331568  0.152279   0.104523  0.137861
16    10.0  2.0  0.5   0.426330  0.232912   0.095581  0.112947
17    10.0  2.0  0.6   0.532830  0.287877   0.074584  0.115497
18    10.0  2.0  0.7   0.583517  0.343088   0.082707  0.113223
19    10.0  2.0  0.8   0.702999  0.413186   0.073576  0.130910
20    10.0  2.0  0.9   0.767437  0.435526   0.067583  0.133632
21    25.0  0.5  0.3   0.277310  0.213073   0.042160  0.043790
22    25.0  0.5  0.4   0.368595  0.308074   0.034082  0.036722
23    25.0  0.5  0.5   0.463384  0.398922   0.031010  0.036073
24    25.0  0.5  0.6   0.555257  0.484534   0.030705  0.036037
25    25.0  0.5  0.7   0.660295  0.583127   0.024186  0.028551
26    25.0  0.5  0.8   0.751737  0.655464   0.019087  0.028508
27    25.0  0.5  0.9   0.847021  0.739539   0.013410  0.026455
28    25.0  1.0  0.3   0.259031  0.205454   0.039178  0.041074
29    25.0  1.0  0.4   0.368689  0.307611   0.035420  0.040143
..     ...  ...  ...        ...       ...        ...       ...
54    50.0  1.0  0.8   0.770095  0.726847   0.008842  0.011403
55    50.0  1.0  0.9   0.871730  0.816501   0.005869  0.009014
56    50.0  2.0  0.3   0.285893  0.256613   0.020418  0.020859
57    50.0  2.0  0.4   0.385863  0.355106   0.017312  0.017750
58    50.0  2.0  0.5   0.477130  0.439420   0.013496  0.014765
59    50.0  2.0  0.6   0.571909  0.535081   0.014034  0.015816
60    50.0  2.0  0.7   0.683227  0.646599   0.010792  0.012681
61    50.0  2.0  0.8   0.772137  0.725381   0.008502  0.010329
62    50.0  2.0  0.9   0.866096  0.816338   0.006491  0.010031
63   100.0  0.5  0.3   0.290206  0.277944   0.010101  0.010262
64   100.0  0.5  0.4   0.395485  0.381141   0.008059  0.008513
65   100.0  0.5  0.5   0.489473  0.473511   0.007223  0.007795
66   100.0  0.5  0.6   0.584692  0.567132   0.006866  0.007087
67   100.0  0.5  0.7   0.685044  0.667165   0.005302  0.005500
68   100.0  0.5  0.8   0.783416  0.762968   0.004229  0.004688
69   100.0  0.5  0.9   0.883556  0.860942   0.002756  0.003286
70   100.0  1.0  0.3   0.291734  0.276623   0.009387  0.009481
71   100.0  1.0  0.4   0.387395  0.375450   0.008476  0.008560
72   100.0  1.0  0.5   0.491658  0.478633   0.007339  0.007495
73   100.0  1.0  0.6   0.586822  0.567715   0.006806  0.007212
74   100.0  1.0  0.7   0.681481  0.662716   0.006052  0.006558
75   100.0  1.0  0.8   0.780024  0.759609   0.003711  0.004476
76   100.0  1.0  0.9   0.886366  0.862276   0.002285  0.003179
77   100.0  2.0  0.3   0.296387  0.282951   0.009373  0.009351
78   100.0  2.0  0.4   0.398754  0.382734   0.008804  0.009276
79   100.0  2.0  0.5   0.496603  0.480024   0.007580  0.007591
80   100.0  2.0  0.6   0.585593  0.569453   0.006302  0.006584
81   100.0  2.0  0.7   0.686151  0.668079   0.005481  0.005838
82   100.0  2.0  0.8   0.784818  0.763092   0.004483  0.005392
83   100.0  2.0  0.9   0.878096  0.855711   0.002575  0.003117

[84 rows x 7 columns]

In [22]:
model1 = smf.ols('E_b_nocon~sample+rho+sig',data=df).fit()
model1.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:              E_b_nocon   R-squared:                       0.991
Model:                            OLS   Adj. R-squared:                  0.990
Method:                 Least Squares   F-statistic:                     2794.
Date:                Thu, 21 Jun 2018   Prob (F-statistic):           7.56e-81
Time:                        18:57:11   Log-Likelihood:                 215.02
No. Observations:                  84   AIC:                            -422.0
Df Residuals:                      80   BIC:                            -412.3
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [95.0% Conf. Int.]
------------------------------------------------------------------------------
Intercept     -0.0469      0.008     -5.724      0.000        -0.063    -0.031
sample         0.0007   6.12e-05     11.968      0.000         0.001     0.001
rho            0.9494      0.010     90.772      0.000         0.929     0.970
sig            0.0010      0.003      0.309      0.758        -0.006     0.008
==============================================================================
Omnibus:                        5.946   Durbin-Watson:                   0.725
Prob(Omnibus):                  0.051   Jarque-Bera (JB):                6.053
Skew:                          -0.650   Prob(JB):                       0.0485
Kurtosis:                       2.806   Cond. No.                         345.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [27]:
model15 = smf.ols('np.log(E_b_nocon)~np.log(sample)+np.log(sample-1)+np.log(rho)',data=df).fit()
model15.summary()
model16 = smf.ols('np.log(I(rho-E_b_nocon))~np.log(sample)+np.log(rho)',data=df).fit()
model16.summary()
np.exp(0.1861)

1.2045427086259795

In [30]:
model2 = smf.ols('E_b_con~sample+rho+sig',data=df).fit()
model2.summary()
model25 = smf.ols('np.log(I(rho-E_b_con))~np.log(sample)+np.log(1+rho)',data=df).fit()
model25.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                               OLS Regression Results                               
====================================================================================
Dep. Variable:     np.log(I(rho - E_b_con))   R-squared:                       0.990
Model:                                  OLS   Adj. R-squared:                  0.990
Method:                       Least Squares   F-statistic:                     4118.
Date:                      Thu, 21 Jun 2018   Prob (F-statistic):           3.44e-82
Time:                              19:06:36   Log-Likelihood:                 82.230
No. Observations:                        84   AIC:                            -158.5
Df Residuals:                            81   BIC:                            -151.2
Df Model:                                 2                                         
Covariance Type:                  nonrobust                                         
===================================================================================
                      coef    std err          t      P>|t|      [95.0% Conf. Int.]
-----------------------------------------------------------------------------------
Intercept           0.3906      0.057      6.907      0.000         0.278     0.503
np.log(sample)     -1.0408      0.012    -87.786      0.000        -1.064    -1.017
np.log(1 + rho)     1.8385      0.080     22.996      0.000         1.679     1.998
==============================================================================
Omnibus:                       10.741   Durbin-Watson:                   1.794
Prob(Omnibus):                  0.005   Jarque-Bera (JB):               10.943
Skew:                          -0.764   Prob(JB):                      0.00421
Kurtosis:                       3.890   Cond. No.                         33.7
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [32]:
np.exp(0.3906)

1.4778672482686943